version: '3.8'
services:
  localstack:
    image: localstack/localstack:latest
    ports:
      - "4566:4566"       # LocalStack edge port
      - "4575:4575"       # SNS
      - "4576:4576"       # SQS
    environment:
      - SERVICES=sns,sqs
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
#    volumes:
#      - "./localstack:/tmp/localstack"